export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const USER_LOADED = "USER_LOADED";
export const AUTHENTICATE_ERROR = "AUTHENTICATE_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const ACCTIVATE_SUCCESS = "ACCTIVATE_SUCCESS";
export const ACCTIVATE_FAILED = "ACCTIVATE_FAILED";

export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAILED = "FORGOT_FAILED";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILED = "RESET_FAILED";

export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILED = "GOOGLE_LOGIN_FAILED";

export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAILED = "FACEBOOK_LOGIN_FAILED";

export const GET_PROPERTY = "GET_PROPERTY";
export const GET_PROPERTYS = "GET_PROPERTYS";
export const GET_MY_PROPERTYS = "GET_MY_PROPERTYS";
export const GET_LIKED_LISTS = "GET_LIKED_LISTS";
export const GET_SEARCHED_LISTS = "GET_SEARCHED_LISTS";
export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const CLEAR_PROPERTY_PROFILE = "CLEAR_PROPERTY_PROFILE";
export const CLEAR_PROPERTY = "CLEAR_PROPERTY";

// export const PROPERTY_ERROR = "PROPERTY_ERROR";
export const UPDATE_INTERESTS = "UPDATE_INTERESTS";

export const ADD_IMAGE = "ADD_IMAGE";
export const GET_MAP = "GET_MAP";

export const REMOVE_IMAGE = "REMOVE_IMAGE";

export const ADD_LIKE = "ADD_LIKE";
export const UNLIKE = "UNLIKE";

export const PROPERTY_ERROR = "PROPERTY_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
